//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9148
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9148.
// 
namespace IHeadChecking.IHeadService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://10.11.1.28/iheadservice/service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClientVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetClientVersion() {
            object[] results = this.Invoke("GetClientVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetClientVersion(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetClientVersion", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetClientVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadScannedBarcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UploadScannedResult UploadScannedBarcode(UploadScannedBarcodeTableRow[] scannedBarcodes) {
            object[] results = this.Invoke("UploadScannedBarcode", new object[] {
                        scannedBarcodes});
            return ((UploadScannedResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUploadScannedBarcode(UploadScannedBarcodeTableRow[] scannedBarcodes, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadScannedBarcode", new object[] {
                        scannedBarcodes}, callback, asyncState);
        }
        
        /// <remarks/>
        public UploadScannedResult EndUploadScannedBarcode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UploadScannedResult)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadScannedBarcodeTableRow {
        
        private string constructionCodeField;
        
        private string houseCodeField;
        
        private string panelNoField;
        
        private string pitchSizeField;
        
        private int scannedFlgField;
        
        private int statusField;
        
        private string employeeCodeField;
        
        private string errMsgField;
        
        /// <remarks/>
        public string ConstructionCode {
            get {
                return this.constructionCodeField;
            }
            set {
                this.constructionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HouseCode {
            get {
                return this.houseCodeField;
            }
            set {
                this.houseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PanelNo {
            get {
                return this.panelNoField;
            }
            set {
                this.panelNoField = value;
            }
        }
        
        /// <remarks/>
        public string PitchSize {
            get {
                return this.pitchSizeField;
            }
            set {
                this.pitchSizeField = value;
            }
        }
        
        /// <remarks/>
        public int ScannedFlg {
            get {
                return this.scannedFlgField;
            }
            set {
                this.scannedFlgField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string EmployeeCode {
            get {
                return this.employeeCodeField;
            }
            set {
                this.employeeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadScannedResult {
        
        private int serverStatusField;
        
        private string serverMessageField;
        
        private UploadScannedBarcodeTableRow[] uploadedDataField;
        
        /// <remarks/>
        public int ServerStatus {
            get {
                return this.serverStatusField;
            }
            set {
                this.serverStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ServerMessage {
            get {
                return this.serverMessageField;
            }
            set {
                this.serverMessageField = value;
            }
        }
        
        /// <remarks/>
        public UploadScannedBarcodeTableRow[] UploadedData {
            get {
                return this.uploadedDataField;
            }
            set {
                this.uploadedDataField = value;
            }
        }
    }
}
